language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t adithya-tech/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true adithya-tech/docker-react npm run test